version: "3.0"
services:
  mariadb:
    image: mariadb:10.10
    environment:
      MYSQL_ROOT_PASSWORD: root1337

    networks:
      - default

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database:/etc/mysql/conf.d:ro

    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  mangosd:
    image: scarabol/cmangos-tbc:latest
    depends_on:
      mariadb:
        condition: service_healthy

    environment:
      MANGOS_DBHOST: mariadb
      MANGOS_DBUSER: mangos
      MANGOS_DBPASS: mangos1337

    command: mangosd
    stdin_open: true
    tty: true
    networks:
      - default

    ports:
      - "8085:8085"

    volumes:
      - mangosd_data:/var/lib/mangos:ro
      - mangosd_conf:/opt/mangos/etc

  realmd:
    image: scarabol/cmangos-tbc:latest
    depends_on:
      mariadb:
        condition: service_healthy

    environment:
      MANGOS_DBHOST: mariadb
      MANGOS_DBUSER: mangos
      MANGOS_DBPASS: mangos1337

    command: realmd
    networks:
      - default

    ports:
      - "3724:3724"

networks:
  default:

volumes:
  mariadb_data:
  mangosd_data:
  mangosd_conf:
